title: ChimeraGaming
description: Retro modding, guides, and tools — EZ-Flash, Vita, 3DS, and more.
url: https://chimeragaming.github.io
baseurl: ""                     # ➕ important for user sites (leave empty)

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

custom_css:
  - /assets/css/guide.css
  - /assets/css/projects.css

search: true
search_full_content: true       # ➕ index full page content
search_provider: lunr           # ➕ explicit (default, but good to set)

author:
  name: ChimeraGaming
  links:
    - label: GitHub
      icon: fab fa-github
      url: https://github.com/ChimeraGaming
    - label: Modded In The Valley
      icon: fas fa-tools
      url: https://www.facebook.com/ModdedInTheValley/
